"use client";
import { randomId } from "@/lib/random-id";
import { createContext, useContext, useState } from "react";
import { ArrowDown, ArrowUp, ChevronDown, ChevronRight, Copy, Plus, Trash2 } from "lucide-react";
import type { Json } from "@/lib/cms/types";
export type References={institutions:{value:number;label:string}[];industries:{value:number;label:string}[]};
const ReferenceContext=createContext<References|undefined>(undefined);
export const ReferencesProvider=ReferenceContext.Provider;
const labels:Record<string,string>={th:'Порог гранта, баллы ЕНТ',inds:'Отрасли',nOps:'Количество программ',source:'Источник / раздел пособия',institutionId:'Учебное заведение',groupCode:'Группа / направление',threshold:'Проходной балл',language:'Язык обучения',exams:'Предметы для поступления',name:'Название',title:'Заголовок',description:'Описание',desc:'Описание',text:'Текст',about:'О программе',fit:'Кому подойдёт',skills:'Навыки',format:'Формат',roles:'Профессии и роли',notfor:'Кому не подойдёт',accent:'Акцентный цвет',accentB:'Второй цвет',tint:'Цвет фона',id:'Идентификатор',i:'Идентификатор заведения',code:'Код',slug:'Адрес',kind:'Тип',type:'Тип',city:'Город',country:'Страна',obl:'Регион',nameKz:'Название на казахском',addr:'Адрес',phone:'Телефон',email:'Email',site:'Сайт',ig:'Instagram',detail:'Подробная информация',ops:'Образовательные программы',univ:'Связи с университетами',p:'Стоимость обучения, ₸',t:'Проходной балл',e:'Экзамены',l:'Язык обучения',g:'Направление / группа',dur:'Срок обучения',no:'Количество программ',nu:'Количество вузов',ind:'Отрасль',ent:'Предметы ЕНТ',langs:'Языки',profs:'Профессии',groups:'Направления',programs:'Программы',cols:'Колледжи',unis:'Университеты',cities:'Города',regs:'Регионы',v:'Вузы',c:'Колледжи',dorm:'Общежитие',mil:'Военная кафедра',mob:'Академическая мобильность',price:'Стоимость',score:'Балл',en:'Название на английском',ru:'Русский',kk:'Қазақша',h1:'Главный заголовок',h2:'Заголовок раздела',eyebrow:'Надзаголовок',lede:'Описание',cta:'Текст кнопки',micro:'Пояснение под кнопкой',meta:'Дополнительные подписи',b:'Основная подпись',s:'Пояснение',href:'Ссылка',label:'Подпись',q:'Вопрос',a:'Ответ',items:'Элементы',list:'Список',blocks:'Блоки урока',options:'Варианты ответа',correct:'Правильный ответ',ok:'Обратная связь: верно',noText:'Обратная связь: неверно',model:'Образец ответа',tText:'Текст варианта',chip:'Подпись типа вопроса',num:'Номер',minutes:'Длительность, минут',note:'Примечание',points:'Баллы',value:'Значение',url:'Ссылка',video:'Видео',icon:'Значок',image:'Изображение',photoUrl:'Ссылка на фото',website:'Сайт',address:'Адрес',shortName:'Короткое название',duration:'Длительность',perks:'Преимущества',method:'Методика',tagline:'Краткое описание',firstName:'Имя',lastName:'Фамилия',school:'Школа',grade:'Класс',region:'Регион',done:'Выполнено',status:'Статус',hint:'Подсказка',k:'Количество программ',d9:'После 9 класса',d11:'После 11 класса',industries:'Отрасли',rank:'Порядок отраслей',obls:'Регионы',regionCities:'Города по регионам',short:'Короткое название',cl:'Цвет фона',fileUrl:'Ссылка на файл',match:'Совпадение, %',count:'Количество',body:'Текст',summary:'Краткий итог',intro:'Введение',outro:'Заключение',heading:'Заголовок',subtitle:'Подзаголовок',learning:'Чему научится ученик',result:'Результат',spec:'Специальности',priceTxt:'Стоимость обучения',lang:'Язык',docs:'Документы для поступления'};
export function fieldLabel(key:string) {return labels[key] || (/^x?\d+$/.test(key)?`${key.startsWith('x')?'Подпись':'Текст'} ${Number(key.replace('x',''))}`:key.replace(/([a-z])([A-Z])/g,'$1 $2'));}
export function TextField({label,value,onChange,multiline=false,readOnly=false}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;readOnly?:boolean}) {
  return <label className={`admin-field ${multiline?'wide':''}`}><span>{label}</span>{multiline?<textarea className="admin-input" rows={3} value={value} readOnly={readOnly} onChange={e=>onChange(e.target.value)}/>:<input className="admin-input" value={value} readOnly={readOnly} onChange={e=>onChange(e.target.value)}/>}</label>;
}
export function OrderButtons({index,length,move,duplicate,remove}:{index:number;length:number;move:(to:number)=>void;duplicate:()=>void;remove:()=>void}) {
  return <div className="flex gap-1"><button type="button" className="admin-btn ghost icon" aria-label="Переместить вверх" disabled={index===0} onClick={()=>move(index-1)}><ArrowUp size={13}/></button><button type="button" className="admin-btn ghost icon" aria-label="Переместить вниз" disabled={index===length-1} onClick={()=>move(index+1)}><ArrowDown size={13}/></button><button type="button" className="admin-btn ghost icon" aria-label="Дублировать" onClick={duplicate}><Copy size={13}/></button><button type="button" className="admin-btn ghost icon danger" aria-label="Удалить элемент" disabled={length<=1} onClick={remove}><Trash2 size={13}/></button></div>;
}
export function moveItem<T>(array:T[],from:number,to:number) {const result=[...array];result.splice(to,0,result.splice(from,1)[0]);return result;}
function cloneItem(value:Json):Json {const copy=structuredClone(value);if(copy&&typeof copy==='object'&&!Array.isArray(copy)){if('id'in copy)copy.id='item-'+randomId().slice(0,8);if('code'in copy)copy.code='new-'+randomId().slice(0,8);}return copy;}
function titleOf(v:Json,i:number) {if(v&&typeof v==='object'&&!Array.isArray(v)){const s=v.title||v.name||v.q||v.label||v.code;return typeof s==='string'?s:`Элемент ${i+1}`;}return `Элемент ${i+1}`;}
function Fold({label,children,initial=false}:{label:string;children:React.ReactNode;initial?:boolean}) {const [open,setOpen]=useState(initial);return <div className="admin-fold"><div className="admin-fold-head"><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<span>{label}</span></button></div>{open&&<div className="admin-fold-body">{children}</div>}</div>;}
export default function ValueEditor({value,onChange,label='Содержание',field='',depth=0,filter=''}:{value:Json;onChange:(v:Json)=>void;label?:string;field?:string;depth?:number;filter?:string}) {
  const [limit,setLimit]=useState(20);
  const references=useContext(ReferenceContext);
  const choices=references&&(['cols','unis','institutions'].includes(field)?references.institutions:['inds','ind'].includes(field)?references.industries:null);
  if(choices&&(typeof value==='number'||(field==='ind'&&typeof value==='string')))return <label className="admin-field"><span>{label}</span><select className="admin-input" value={value} onChange={e=>onChange(typeof value==='number'?Number(e.target.value):e.target.value)}>{choices.map(c=><option key={c.value} value={typeof value==='number'?c.value:c.label}>{c.label}</option>)}</select></label>;
  if(Array.isArray(value))return <div>{value.map((item,i)=>({item,i})).filter(({item})=>!filter||JSON.stringify(item).toLocaleLowerCase('ru').includes(filter.toLocaleLowerCase('ru'))).slice(0,limit).map(({item,i})=><div className="admin-list-item" key={item&&typeof item==='object'&&!Array.isArray(item)&&typeof item.id==='string'?item.id:i}><div className="admin-question-head"><span>{i+1} / {value.length}</span><OrderButtons index={i} length={value.length} move={to=>onChange(moveItem(value,i,to))} duplicate={()=>onChange([...value.slice(0,i+1),cloneItem(item),...value.slice(i+1)])} remove={()=>onChange(value.filter((_,j)=>j!==i))}/></div>{item&&typeof item==='object'?<Fold label={titleOf(item,i)} initial={value.length<=3}><ValueEditor value={item} onChange={v=>onChange(value.map((old,j)=>j===i?v:old))} depth={depth+1}/></Fold>:<ValueEditor field={field} label={`${label} ${i+1}`} value={item} onChange={v=>onChange(value.map((old,j)=>j===i?v:old))} depth={depth+1}/>}</div>)}{value.length>limit&&<button className="admin-btn" onClick={()=>setLimit(limit+30)}>Показать ещё</button>}<button type="button" className="admin-add" onClick={()=>{onChange([...value,value.length?cloneItem(value[value.length-1]):'']);setLimit(value.length+1);}}><Plus size={13} className="inline mr-2"/>Добавить элемент</button></div>;
  if(value!==null && typeof value==='object') {
    const entries=Object.entries(value).filter(([k])=>k!=='institutionId'&&!(field==='detail'&&k==='ops')).filter(([k,v])=>!filter||`${fieldLabel(k)} ${JSON.stringify(v)}`.toLocaleLowerCase('ru').includes(filter.toLocaleLowerCase('ru')));
    const primitive=entries.filter(([,v])=>v===null||typeof v!=='object'),nested=entries.filter(([,v])=>v!==null&&typeof v==='object');
    return <><div className="admin-fields">{primitive.map(([k,v])=>k==='type'&&typeof value.q==='string'?<label className="admin-field" key={k}><span>Тип вопроса</span><select className="admin-input" value={String(v)} onChange={e=>onChange({...value,type:e.target.value,chip:e.target.value==='single'?'Один ответ':e.target.value==='multi'?'Несколько ответов':'Открытый ответ',...(e.target.value!=='open'&&!Array.isArray(value.options)?{options:[{t:'',correct:false},{t:'',correct:false}]}:{})})}><option value="single">Один правильный ответ</option><option value="multi">Несколько правильных ответов</option><option value="open">Открытый ответ</option></select></label>:k==='kind'&&typeof v==='string'&&['terms','list','note','key'].includes(v)?<label key={k} className="admin-field"><span>Тип блока урока</span><select className="admin-input" value={v} onChange={e=>onChange({...value,kind:e.target.value,...(e.target.value==='note'?{text:value.text||''}:{items:value.items||[{t:'',d:''}]}),title:value.title||''})}><option value="terms">Термины с пояснениями</option><option value="list">Список</option><option value="note">Примечание</option><option value="key">Ключевая мысль</option></select></label>:<ValueEditor key={k} field={k} label={field==='detail'&&k==='about'?'О заведении':k==='t'&&typeof v==='string'?'Текст ответа':k==='no'&&typeof v==='string'?'Обратная связь: неверно':fieldLabel(k)} value={v} onChange={next=>onChange({...value,[k]:next})} depth={depth+1}/>)}</div>{nested.map(([k,v])=><Fold key={k} label={`${field==="univ" ? references?.institutions.find(i=>String(i.value)===k)?.label || k : fieldLabel(k)}${Array.isArray(v)?' · '+v.length:''}`} initial={depth===0&&nested.length===1}><ValueEditor value={v} field={k} label={fieldLabel(k)} onChange={next=>onChange({...value,[k]:next})} depth={depth+1}/></Fold>)}</>;
  }
  if(typeof value==='boolean')return <label className="admin-field"><span>{label}</span><span style={{display:'flex',gap:9,alignItems:'center',minHeight:42}}><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{value?'Да':'Нет'}</span></label>;
  if(typeof value==='number')return <label className="admin-field"><span>{label}</span><input className="admin-input" type="number" min={0} readOnly={field==='i'||field==='institutionId'} value={value} onChange={e=>onChange(e.target.value===''?0:Number(e.target.value))}/></label>;
  if(value===null)return <label className="admin-field"><span>{label} · не указано</span><input className="admin-input" placeholder="Оставьте пустым или укажите значение" value="" onChange={e=>onChange(e.target.value===''?null:/^-?\d+(\.\d+)?$/.test(e.target.value)?Number(e.target.value):e.target.value)}/></label>;
  return <TextField label={label} value={value} onChange={onChange} readOnly={['id','slug'].includes(field)||field==='code'&&depth===1||field==='kind'&&depth===1} multiline={value.length>85||/^(text|description|desc|about|fit|skills|format|roles|notfor|q|a|body|summary|lede|tagline|model|ok|no)$/.test(field)||/^\d+$/.test(field)}/>;
}
